export const clubWorldCup = {
  groups: [
    {
      id: "A",
      name: "Grupa A",
      teams: [
        { id: 1, name: "Palmeiras", logo: "/logos/palmeiras.png", points: 0, played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0 },
        { id: 2, name: "FC Porto", logo: "/logos/porto.png", points: 0, played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0 },
        { id: 3, name: "Al Ahly", logo: "/logos/ahli.png", points: 0, played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0 },
        { id: 4, name: "Inter Miami", logo: "/logos/intermiami.png", points: 0, played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0 },
      ],
      fixtures: [
        { date: "2025-06-10", time: "18:00", home: "Palmeiras", away: "FC Porto", score: null },
        { date: "2025-06-12", time: "21:00", home: "Al Ahly", away: "Inter Miami", score: null },
        { date: "2025-06-15", time: "19:00", home: "Palmeiras", away: "Al Ahly", score: null },
        { date: "2025-06-17", time: "20:00", home: "FC Porto", away: "Inter Miami", score: null },
        { date: "2025-06-20", time: "18:00", home: "Inter Miami", away: "Palmeiras", score: null },
        { date: "2025-06-22", time: "21:00", home: "FC Porto", away: "Al Ahly", score: null },
      ],
    },
    {
      id: "B",
      name: "Grupa B",
      teams: [
        { id: 5, name: "Paris Saint-Germain", logo: "/logos/psg.png", points: 0, played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0 },
        { id: 6, name: "Atlético Madrid", logo: "/logos/atletico.png", points: 0, played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0 },
        { id: 7, name: "Botafogo", logo: "/logos/botafogo.png", points: 0, played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0 },
        { id: 8, name: "Seattle Sounders", logo: "/logos/seattle.png", points: 0, played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0 },
      ],
      fixtures: [
        { date: "2025-06-11", time: "19:00", home: "Paris Saint-Germain", away: "Atlético Madrid", score: null },
        { date: "2025-06-13", time: "20:00", home: "Botafogo", away: "Seattle Sounders", score: null },
        { date: "2025-06-16", time: "18:30", home: "Atlético Madrid", away: "Botafogo", score: null },
        { date: "2025-06-18", time: "21:00", home: "Seattle Sounders", away: "Paris Saint-Germain", score: null },
        { date: "2025-06-21", time: "19:00", home: "Seattle Sounders", away: "Atlético Madrid", score: null },
        { date: "2025-06-23", time: "20:00", home: "Botafogo", away: "Paris Saint-Germain", score: null },
      ],
    },
    {
      id: "C",
      name: "Grupa C",
      teams: [
        { id: 9, name: "Bayern Munich", logo: "/logos/bayern.png", points: 0, played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0 },
        { id: 10, name: "Benfica", logo: "/logos/benfica.png", points: 0, played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0 },
        { id: 11, name: "Boca Juniors", logo: "/logos/boca.png", points: 0, played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0 },
        { id: 12, name: "Auckland City", logo: "/logos/auckland.png", points: 0, played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0 },
      ],
      fixtures: [
        { date: "2025-06-10", time: "17:00", home: "Bayern Munich", away: "Benfica", score: null },
        { date: "2025-06-12", time: "19:00", home: "Boca Juniors", away: "Auckland City", score: null },
        { date: "2025-06-14", time: "18:00", home: "Bayern Munich", away: "Boca Juniors", score: null },
        { date: "2025-06-16", time: "20:00", home: "Benfica", away: "Auckland City", score: null },
        { date: "2025-06-18", time: "19:00", home: "Auckland City", away: "Bayern Munich", score: null },
        { date: "2025-06-20", time: "21:00", home: "Benfica", away: "Boca Juniors", score: null },
      ],
    },
    {
      id: "D",
      name: "Grupa D",
      teams: [
        { id: 13, name: "Flamengo", logo: "/logos/flamengo.png", points: 0, played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0 },
        { id: 14, name: "Chelsea", logo: "/logos/chelsea.png", points: 0, played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0 },
        { id: 15, name: "Esperance Sportive de Tunis", logo: "/logos/tunisie.png", points: 0, played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0 },
        { id: 16, name: "Los Angeles FC", logo: "/logos/lafc.png", points: 0, played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0 },
      ],
      fixtures: [
        { date: "2025-06-11", time: "17:30", home: "Flamengo", away: "Chelsea", score: null },
        { date: "2025-06-13", time: "19:30", home: "Esperance Sportive de Tunis", away: "Los Angeles FC", score: null },
        { date: "2025-06-15", time: "21:00", home: "Flamengo", away: "Esperance Sportive de Tunis", score: null },
        { date: "2025-06-17", time: "18:00", home: "Chelsea", away: "Los Angeles FC", score: null },
        { date: "2025-06-19", time: "20:00", home: "Los Angeles FC", away: "Flamengo", score: null },
        { date: "2025-06-21", time: "22:00", home: "Chelsea", away: "Esperance Sportive de Tunis", score: null },
      ],
    },
    {
      id: "E",
      name: "Grupa E",
      teams: [
        { id: 17, name: "River Plate", logo: "/logos/river.png", points: 0, played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0 },
        { id: 18, name: "Inter Milan", logo: "/logos/inter.png", points: 0, played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0 },
        { id: 19, name: "CF Monterrey", logo: "/logos/monterrey.png", points: 0, played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0 },
        { id: 20, name: "Urawa Red Diamonds", logo: "/logos/diamonds.png", points: 0, played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0 },
      ],
      fixtures: [
        { date: "2025-06-10", time: "18:30", home: "River Plate", away: "Inter Milan", score: null },
        { date: "2025-06-12", time: "20:00", home: "CF Monterrey", away: "Urawa Red Diamonds", score: null },
        { date: "2025-06-14", time: "19:30", home: "River Plate", away: "CF Monterrey", score: null },
        { date: "2025-06-16", time: "21:00", home: "Inter Milan", away: "Urawa Red Diamonds", score: null },
        { date: "2025-06-18", time: "20:00", home: "Urawa Red Diamonds", away: "River Plate", score: null },
        { date: "2025-06-20", time: "22:00", home: "Inter Milan", away: "CF Monterrey", score: null },
      ],
    },
    {
      id: "F",
      name: "Grupa F",
      teams: [
        { id: 21, name: "Fluminense", logo: "/logos/fluminense.png", points: 0, played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0 },
        { id: 22, name: "Borussia Dortmund", logo: "/logos/bvb.png", points: 0, played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0 },
        { id: 23, name: "Ulsan Hyundai", logo: "/logos/ulsan.png", points: 0, played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0 },
        { id: 24, name: "Mamelodi Sundowns", logo: "/logos/mamelodi.png", points: 0, played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0 },
      ],
      fixtures: [
        { date: "2025-06-11", time: "18:00", home: "Fluminense", away: "Borussia Dortmund", score: null },
        { date: "2025-06-13", time: "20:30", home: "Ulsan Hyundai", away: "Mamelodi Sundowns", score: null },
        { date: "2025-06-15", time: "19:00", home: "Fluminense", away: "Ulsan Hyundai", score: null },
        { date: "2025-06-17", time: "21:00", home: "Borussia Dortmund", away: "Mamelodi Sundowns", score: null },
        { date: "2025-06-19", time: "20:00", home: "Mamelodi Sundowns", away: "Fluminense", score: null },
        { date: "2025-06-21", time: "22:00", home: "Borussia Dortmund", away: "Ulsan Hyundai", score: null },
      ],
    },
    {
      id: "G",
      name: "Grupa G",
      teams: [
        { id: 25, name: "Manchester City", logo: "/logos/mancity.png", points: 0, played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0 },
        { id: 26, name: "Juventus", logo: "/logos/juventus.png", points: 0, played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0 },
        { id: 27, name: "Wydad AC", logo: "/logos/wydad.png", points: 0, played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0 },
        { id: 28, name: "Al Ain", logo: "/logos/ain.png", points: 0, played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0 },
      ],
      fixtures: [
        { date: "2025-06-10", time: "19:00", home: "Manchester City", away: "Juventus",  score: null },
        { date: "2025-06-12", time: "21:00", home: "Wydad AC", away: "Al Ain",  score: null },
        { date: "2025-06-14", time: "20:00", home: "Manchester City", away: "Wydad AC",  score: null },
        { date: "2025-06-16", time: "18:00", home: "Juventus", away: "Al Ain",  score: null },
        { date: "2025-06-18", time: "19:30", home: "Al Ain", away: "Manchester City",  score: null },
        { date: "2025-06-20", time: "21:30", home: "Juventus", away: "Wydad AC",  score: null },
      ],
    },
    {
      id: "H",
      name: "Grupa H",
      teams: [
        { id: 29, name: "Real Madrid", logo: "/logos/realmadrid.png", points: 0, played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0 },
        { id: 30, name: "FC Salzburg", logo: "/logos/salzburg.png", points: 0, played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0 },
        { id: 31, name: "Al Hilal", logo: "/logos/alhilal.png", points: 0, played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0 },
        { id: 32, name: "CF Pachuca", logo: "/logos/pachuca.png", points: 0, played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0 },
      ],
      fixtures: [
        { date: "2025-06-11", time: "18:30", home: "Real Madrid", away: "FC Salzburg",  score: null },
        { date: "2025-06-13", time: "20:30", home: "Al Hilal", away: "CF Pachuca",  score: null },
        { date: "2025-06-15", time: "19:00", home: "Real Madrid", away: "Al Hilal", score: null },
        { date: "2025-06-17", time: "21:00", home: "FC Salzburg", away: "CF Pachuca",  score: null },
        { date: "2025-06-19", time: "20:00", home: "CF Pachuca", away: "Real Madrid",  score: null },
        { date: "2025-06-21", time: "22:00", home: "FC Salzburg", away: "Al Hilal",  score: null },
      ],
    },
  ],
};
