export const channels = [
  {
    id: 1,
    name: "Antena 1",
    category: "General",
    thumbnail: "/thumbnails/antena1.png",
    iframeUrl: "https://canale-tv.com/channel/a1.html",
  },
  {
    id: 2,
    name: "Digi Sport 1",
    category: "Sport",
    thumbnail: "/thumbnails/DigiSport.jpg",
    iframeUrl: "https://canale-tv.com/channel/dgsp1.html",
  },
  {
    id: 3,
    name: "Digi Sport 2",
    category: "Sport",
    thumbnail: "/thumbnails/DigiSport.jpg",
    iframeUrl: "https://canale-tv.com/channel/dgsp2.html",
  },
  {
    id: 4,
    name: "Digi Sport 3",
    category: "Sport",
    thumbnail: "/thumbnails/DigiSport.jpg",
    iframeUrl: "https://canale-tv.com/channel/dgsp3.html",
  },
  {
    id: 5,
    name: "Digi Sport 4",
    category: "Sport",
    thumbnail: "/thumbnails/DigiSport.jpg",
    iframeUrl: "https://canale-tv.com/channel/dgsp4.html",
  },
  {
    id: 6,
    name: "Eurosport 1",
    category: "Sport",
    thumbnail: "/thumbnails/eurosport.jpg",
    iframeUrl: "https://canale-tv.com/channel/eurosp1.html",
  },
  {
    id: 7,
    name: "Eurosport 2",
    category: "Sport",
    thumbnail: "/thumbnails/eurosport.jpg",
    iframeUrl: "https://canale-tv.com/channel/eurosp2.html",
  },
  {
    id: 8,
    name: "Kiss TV",
    category: "Muzica",
    thumbnail: "/thumbnails/kisstv.jpg",
    iframeUrl: "https://canale-tv.com/channel/kisstv.html",
  },
  {
    id: 9,
    name: "Prima Sport 1",
    category: "Sport",
    thumbnail: "/thumbnails/primasport.jpg",
    iframeUrl: "https://canale-tv.com/channel/primasp2.html",
  },
  {
    id: 10,
    name: "Prima Sport 2",
    category: "Sport",
    thumbnail: "/thumbnails/primasport.jpg",
    iframeUrl: "https://canale-tv.com/channel/primasp2.html",
  },
  {
    id: 11,
    name: "Prima Sport 3",
    category: "Sport",
    thumbnail: "/thumbnails/primasport.jpg",
    iframeUrl: "https://canale-tv.com/channel/primasp3.html",
  },
  {
    id: 12,
    name: "Prima Sport 4",
    category: "Sport",
    thumbnail: "/thumbnails/primasport.jpg",
    iframeUrl: "https://canale-tv.com/channel/primasp4.html",
  },
  {
    id: 13,
    name: "Prima Sport 5",
    category: "Sport",
    thumbnail: "/thumbnails/primasport.jpg",
    iframeUrl: "https://canale-tv.com/channel/primasp5.html",
  },
  {
    id: 14,
    name: "Prima TV",
    category: "General",
    thumbnail: "/thumbnails/primatv.jpg",
    iframeUrl: "https://canale-tv.com/channel/primatv.html",
  },
  {
    id: 15,
    name: "Pro Arena",
    category: "Sport",
    thumbnail: "/thumbnails/proarena.jpeg",
    iframeUrl: "https://canale-tv.com/channel/proarena.html",
  },
  {
    id: 16,
    name: "Pro TV",
    category: "General",
    thumbnail: "/thumbnails/protv.jpg",
    iframeUrl: "https://canale-tv.com/channel/protv.html",
  },
  {
    id: 17,
    name: "Romania TV",
    category: "Stiri",
    thumbnail: "/thumbnails/rtv.jpg",
    iframeUrl: "https://canale-tv.com/channel/romaniatv.html",
  },
  {
    id: 18,
    name: "TVR 1",
    category: "General",
    thumbnail: "/thumbnails/tvr1.jpeg",
    iframeUrl: "https://canale-tv.com/channel/tvr1.html",
  },
  {
    id: 19,
    name: "TVR Sport",
    category: "Sport",
    thumbnail: "/thumbnails/tvr1.jpeg",
    iframeUrl: "https://canale-tv.com/channel/tvrsport.html",
  },
  {
    id: 20,
    name: "ZU TV",
    category: "Muzica",
    thumbnail: "/thumbnails/zutv.jpeg",
    iframeUrl: "https://canale-tv.com/channel/zutv.html",
  },
];
